### ISSUE TITLE
Request GeofenceStatus.IsInside

### ISSUE THREAD

**Issue by dreamsystems** [aritchie/geofences#1]
Hi, thanks for your plugin. It will be nice to have a `GeofenceStatus.IsInside` feature.
Actually, if a user is inside a geofence area at app initialization, nothing happens. 
Do you have a suggestion to handle this ?
Thanks

**Comment by aritchie** [comment]
This is (mostly) by design.  When the service initializes the first time, it has the geofences setup in an unknown state.  Once the state is known, it proceeds to fire events.  This is to prevent firing an event that didn't actually happen (you were already in or out).  You should run a sticky service in your android app to keep your app hot.  This way, the geofences stay in a known state.

**Comment by dreamsystems** [comment]
Thanks for your quick reply.
